const communities = [
  "Engineering",
  "Nursing",
  "Arts",
  "Commerce",
  "Dentistry",
  "Education",
  "Forestry",
  "Graduate Studies",
  "Interdisciplinary Studies",
  "Law",
  "Pharmacy",
  "Science",
  "Biomedical Engineering",
  "Chemical and Biological Engineering",
  "Civil Engineering",
  "Computer Engineering",
  "Electrical Engineering",
  "Engineering Physics",
  "Environmental Engineering",
  "Geological Engineering",
  "Integrated Engineering",
  "Manufacturing Engineering",
  "Materials Engineering",
  "Mechanical Engineering",
  "Mining Engineering",
  "Chemical Engineering",
  "Architecture",
  "Anthropology",
  "Asian Studies",
  "Art History, Visual Art and Theory",
  "Central, Eastern, and Northern European Studies",
  "Classical, Near Eastern and Religious Studies",
  "Creative Writing",
  "Economics",
  "International Economics",
  "English",
  "French, Hispanic & Italian Studies",
  "Fine Arts",
  "Geography",
  "History",
  "International Relations",
  "Journalism",
  "Linguistics",
  "Media Studies",
  "Philosophy",
  "Political Science",
  "Psychology",
  "Sociology",
  "School of Information",
  "Social Work",
  "Theatre and Film Studies",
  "Accounting",
  "Finance",
  "Law - Commerce",
  "Management Information Systems",
  "Marketing",
  "Master of Business Administration",
  "Master of Management in Operations Research",
  "Operations and Logistics",
  "Organizational Behaviour and Human Resources",
  "Real Estate",
  "Strategy and Business Economics",
  "Middle Years Education",
  "Elementary Education",
  "International Baccalaureate Education",
  "NITEP",
  "Secondary Education",
  "WKTEP",
  "Forest Resources Management",
  "Urban Forestry",
  "Wood Products Processing",
  "Natural Resources Conservation",
  "Forest Sciences",
  "Bioeconomy Science and Technology",
  "Forest Operations",
  "Green College",
  "St. John's College",
  "Botany",
  "Astronomy",
  "Biochemistry",
  "Biology",
  "Biotechnology",
  "Chemistry",
  "Cognitive Systems",
  "Computer Science",
  "Biophysics",
  "CAPS",
  "Combined Major in Science",
  "Environmental Sciences",
  "Earth and Ocean Sciences",
  "Forensic Science",
  "Genetics",
  "Geographical Sciences",
  "Geology",
  "Geophysics",
  "Integrated Sciences",
  "Mathematics",
  "Mathematical Sciences",
  "Microbiology and Immunology",
  "Neuroscience",
  "Physics and Astronomy",
  "Physics",
  "Statistics",
  "Zoology",
  "Applied Biology",
  "Applied Animal Biology",
  "Food, Nutrition & Health",
  "Land and Food Systems",
  "Pharmacology",
  "Alumni",
  "Kinesiology",
  "Music",
  "Planning",
  "UBC Farm",
  "Staff",
  "Prospective Student (Graduate)",
  "Prospective Student (Undergraduate)",
  "Business and Computer Science",
  "Computer Science",
  "Science One",
  "Arts One",
  "Mathematics",
];
export default communities;
